services:
  traefik:
    image: "traefik:v3.4.1"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--accesslog"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--accesslog.format=json"
      - "--accesslog.fields.headers.names.X-Ipcountry=keep"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # Configure Traefik to trust and process X-Real-IP and X-Forwarded-For headers
      # This is essential for the geoblock plugin to see the actual client IPs instead of Docker network IPs
      # Without this, the plugin would only see internal Docker IPs (172.x.x.x) and block legitimate requests
      - "--entrypoints.web.forwardedHeaders.trustedIPs=172.16.0.0/12,192.168.0.0/16,10.0.0.0/8,127.0.0.1/32,::1/128"
      - "--entrypoints.web.forwardedHeaders.insecure=true"

      - "--experimental.localplugins.geoblock.modulename=github.com/david-garcia-garcia/traefik-geoblock"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - logs-local:/var/log/traefik
      - geoblock-logs:/var/log/geoblock
      - './geoblockban.html:/geoblockban.html:ro'
      - ./:/plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock
    ports:
      - 8000:80
      - 8080:8080

  whoami-foo:
    image: traefik/whoami
    container_name: "simple-service-foo"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router-foo.rule=PathPrefix(`/foo`)"
      - "traefik.http.routers.router-foo.entrypoints=web"
      - "traefik.http.routers.router-foo.middlewares=geoblock2@docker"
      - "traefik.http.services.service-foo.loadbalancer.server.port=80"
      - "traefik.http.middlewares.geoblock2.plugin.geoblock.enabled=true"
      - "traefik.http.middlewares.geoblock2.plugin.geoblock.logLevel=DEBUG"
      - "traefik.http.middlewares.geoblock2.plugin.geoblock.logPath="
      - "traefik.http.middlewares.geoblock2.plugin.geoblock.logFormat=JSON"
      - "traefik.http.middlewares.geoblock2.plugin.geoblock.databaseFilePath=/plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock/IP2LOCATION-LITE-DB1.IPV6.BIN"
      - "traefik.http.middlewares.geoblock2.plugin.geoblock.banHtmlFilePath=/plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock/geoblockban.html"
      - "traefik.http.middlewares.geoblock2.plugin.geoblock.allowPrivate=true"
      - "traefik.http.middlewares.geoblock2.plugin.geoblock.blockedCountries=US,CN,RU"
      - "traefik.http.middlewares.geoblock2.plugin.geoblock.allowedCountries=DE,FR,GB"
      - "traefik.http.middlewares.geoblock2.plugin.geoblock.defaultAllow=false"

  whoami2:
    image: traefik/whoami
    container_name: "simple-service-bar"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router-bar.rule=PathPrefix(`/bar`)"
      - "traefik.http.routers.router-bar.entrypoints=web"
      - "traefik.http.routers.router-bar.middlewares=geoblock@docker"
      - "traefik.http.services.service-bar.loadbalancer.server.port=80"
      - "traefik.http.middlewares.geoblock.plugin.geoblock.enabled=true"
      - "traefik.http.middlewares.geoblock.plugin.geoblock.logLevel=DEBUG"
      - "traefik.http.middlewares.geoblock.plugin.geoblock.logPath="
      - "traefik.http.middlewares.geoblock.plugin.geoblock.logFormat=JSON"
      - "traefik.http.middlewares.geoblock.plugin.geoblock.databaseFilePath=/plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock/IP2LOCATION-LITE-DB1.IPV6.BIN"
      - "traefik.http.middlewares.geoblock.plugin.geoblock.banHtmlFilePath=/plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock/geoblockban.html"
      - "traefik.http.middlewares.geoblock.plugin.geoblock.allowPrivate=true"
      - "traefik.http.middlewares.geoblock.plugin.geoblock.blockedCountries=US,CN,RU"
      - "traefik.http.middlewares.geoblock.plugin.geoblock.allowedCountries=DE,FR,GB"
      - "traefik.http.middlewares.geoblock.plugin.geoblock.defaultAllow=false"
      - "traefik.http.middlewares.geoblock.plugin.geoblock.databaseAutoUpdate=true"
      - "traefik.http.middlewares.geoblock.plugin.geoblock.databaseAutoUpdateDir=/data/ip2database"

  whoami-logtest:
    image: traefik/whoami
    container_name: "simple-service-logtest"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router-logtest.rule=PathPrefix(`/logtest`)"
      - "traefik.http.routers.router-logtest.entrypoints=web"
      - "traefik.http.routers.router-logtest.middlewares=geoblock-logtest@docker"
      - "traefik.http.services.service-logtest.loadbalancer.server.port=80"
      - "traefik.http.middlewares.geoblock-logtest.plugin.geoblock.enabled=true"
      - "traefik.http.middlewares.geoblock-logtest.plugin.geoblock.logLevel=INFO"
      - "traefik.http.middlewares.geoblock-logtest.plugin.geoblock.logPath=/var/log/geoblock/geoblock.log"
      - "traefik.http.middlewares.geoblock-logtest.plugin.geoblock.logFormat=json"
      - "traefik.http.middlewares.geoblock-logtest.plugin.geoblock.logBannedRequests=true"
      - "traefik.http.middlewares.geoblock-logtest.plugin.geoblock.databaseFilePath=/plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock/IP2LOCATION-LITE-DB1.IPV6.BIN"
      - "traefik.http.middlewares.geoblock-logtest.plugin.geoblock.banHtmlFilePath=/plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock/geoblockban.html"
      - "traefik.http.middlewares.geoblock-logtest.plugin.geoblock.allowPrivate=true"
      - "traefik.http.middlewares.geoblock-logtest.plugin.geoblock.blockedCountries=US,CN,RU"
      - "traefik.http.middlewares.geoblock-logtest.plugin.geoblock.allowedCountries=DE,FR,GB"
      - "traefik.http.middlewares.geoblock-logtest.plugin.geoblock.defaultAllow=false"

  whoami-countryHeaderTest:
    image: traefik/whoami
    container_name: "simple-service-countryHeaderTest"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router-countryHeaderTest.rule=PathPrefix(`/countryHeaderTest`)"
      - "traefik.http.routers.router-countryHeaderTest.entrypoints=web"
      - "traefik.http.routers.router-countryHeaderTest.middlewares=geoblock-countryHeaderTest@docker"
      - "traefik.http.services.service-countryHeaderTest.loadbalancer.server.port=80"
      - "traefik.http.middlewares.geoblock-countryHeaderTest.plugin.geoblock.enabled=true"
      - "traefik.http.middlewares.geoblock-countryHeaderTest.plugin.geoblock.logLevel=DEBUG"
      - "traefik.http.middlewares.geoblock-countryHeaderTest.plugin.geoblock.logPath="
      - "traefik.http.middlewares.geoblock-countryHeaderTest.plugin.geoblock.logFormat=JSON"
      - "traefik.http.middlewares.geoblock-countryHeaderTest.plugin.geoblock.logBannedRequests=true"
      - "traefik.http.middlewares.geoblock-countryHeaderTest.plugin.geoblock.databaseFilePath=/plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock/IP2LOCATION-LITE-DB1.IPV6.BIN"
      - "traefik.http.middlewares.geoblock-countryHeaderTest.plugin.geoblock.banHtmlFilePath=/plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock/geoblockban.html"
      - "traefik.http.middlewares.geoblock-countryHeaderTest.plugin.geoblock.allowPrivate=true"
      - "traefik.http.middlewares.geoblock-countryHeaderTest.plugin.geoblock.blockedCountries=US,CN,RU"
      - "traefik.http.middlewares.geoblock-countryHeaderTest.plugin.geoblock.allowedCountries=DE,FR,GB"
      - "traefik.http.middlewares.geoblock-countryHeaderTest.plugin.geoblock.defaultAllow=false"
      - "traefik.http.middlewares.geoblock-countryHeaderTest.plugin.geoblock.countryHeader=X-Ipcountry"

  whoami-blockall:
    image: traefik/whoami
    container_name: "simple-service-blockall"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router-blockall.rule=PathPrefix(`/blockall`)"
      - "traefik.http.routers.router-blockall.entrypoints=web"
      - "traefik.http.routers.router-blockall.middlewares=geoblock-blockall@docker"
      - "traefik.http.services.service-blockall.loadbalancer.server.port=80"
      - "traefik.http.middlewares.geoblock-blockall.plugin.geoblock.enabled=true"
      - "traefik.http.middlewares.geoblock-blockall.plugin.geoblock.logLevel=INFO"
      - "traefik.http.middlewares.geoblock-blockall.plugin.geoblock.logPath="
      - "traefik.http.middlewares.geoblock-blockall.plugin.geoblock.logFormat=JSON"
      - "traefik.http.middlewares.geoblock-blockall.plugin.geoblock.logBannedRequests=true"
      - "traefik.http.middlewares.geoblock-blockall.plugin.geoblock.databaseFilePath=/plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock/IP2LOCATION-LITE-DB1.IPV6.BIN"
      - "traefik.http.middlewares.geoblock-blockall.plugin.geoblock.banHtmlFilePath=/plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock/geoblockban.html"
      - "traefik.http.middlewares.geoblock-blockall.plugin.geoblock.allowPrivate=false"
      - "traefik.http.middlewares.geoblock-blockall.plugin.geoblock.allowedCountries="
      - "traefik.http.middlewares.geoblock-blockall.plugin.geoblock.blockedCountries="
      - "traefik.http.middlewares.geoblock-blockall.plugin.geoblock.defaultAllow=false"

volumes:
  logs-local:
  geoblock-logs:
